#!/usr/bin/env bash
# Assuming Matugen generates your colors in a JSON file
MATUGEN_COLOR_FILE="$HOME/.config/matugen/colors.json"

# Extract colors (Vicinae needs hex codes without the #)
BG=$(jq -r '.colors.background' "$MATUGEN_COLOR_FILE")
FG=$(jq -r '.colors.foreground' "$MATUGEN_COLOR_FILE")
ACCENT=$(jq -r '.colors.primary' "$MATUGEN_COLOR_FILE")

# Write to Vicinae's theme file
cat <<EOF > ~/.local/share/vicinae/themes/matugen-dynamic.toml
[meta]
version = 1
name = "Matugen Dynamic"
description = "Theme dynamically generated by Matugen"
variant = "dark"
inherits = "vicinae-dark"

[colors.core]
background = "${BG}"
foreground = "${FG}"
accent = "${ACCENT}"
EOF

# Tell Vicinae to set the theme (or restart it)
# Assuming you use the vicinae binary
vicinae set-theme matugen-dynamic
