# Noctalia Theme for Mango
# Generated automatically by Noctalia

rootcolor = 0x000000ff
bordercolor = 0x716263ff
dropcolor = 0xe4676e80
splitcolor = 0x7766ccff
focuscolor = 0xe4676eff
maximizescreencolor = 0xd6925cff
urgentcolor = 0xb1373eff
scratchpadcolor = 0x7766ccff
globalcolor = 0x85141aff
overlaycolor = 0x6a3b16ff
jump_label_decorate_fg_color = 0xf3f2f2ff
jump_label_decorate_bg_color = 0x280c0eff
jump_label_decorate_focus_fg_color = 0x251819ff
jump_label_decorate_focus_bg_color = 0xe4676eff
jump_label_decorate_border_color = 0x716263ff
group_bar_decorate_fg_color = 0xf3f2f2ff
group_bar_decorate_bg_color = 0x280c0eff
group_bar_decorate_focus_fg_color = 0x251819ff
group_bar_decorate_focus_bg_color = 0xe4676eff
group_bar_decorate_border_color = 0x716263ff
