# colors for fuzzel application launcher
# You can use this template by adding the following to wallust.toml:
# fuzzel = { template = "fuzzel.ini", target = "~/.config/fuzzel/colors.ini" }
# and add the following to your foot.ini config
# [main]
# include=/home/USERNAME/.config/fuzzel/colors.ini


[colors]
background=#1D1D23ff
text=#FFF9E7ff
prompt=#44434Aff
placeholder=#A99FE4ff
input=#F87FCBff
match=#FB9298ff
selection=#F9D0BBff
#selection-text=#FACDE3
selection-text=0000000 #hardcoded to black.... how to make this dynamic and always readable?
selection-match=#FEEEBAff
counter=#F6EED4ff
border=#ACA794ff
