# Start on boot
exec-once = awww-daemon
exec-once = vicinae server
exec-once = ~/.config/scripts/mangoconky.sh

exec-once = foot --server
exec-once = mako
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec-once = wl-paste --type image --watch cliphist store
exec-once = wl-paste --type text --watch cliphist store
exec-once = kdeconnectd
exec-once = kdeconnect-indicator
exec-once = dms run &
