# Border settings
border_radius=0
no_border_when_single=1

# Overview settings
enable_hotarea=0
hotarea_size=10
ov_tab_mode=1
hotarea_corner=0
overviewgappi=10
overviewgappo=10

# Keyboard related
repeat_rate=100
repeat_delay=300
numlockon=0
xkb_rules_layout=us

# Touchpad settings
disable_trackpad=0
tap_and_drag=1
trackpad_natural_scrolling=1
trackpad_accel_profile=2
trackpad_accel_speed=1.0
# disable_while_typing=1
swipe_min_threshold=1
trackpad_scroll_factor=2.0

# Mouse Settings
mouse_natural_scrolling=0
mouse_accel_profile=2
mouse_accel_speed=1.0
# left_handed=0
axis_scroll_factor=2.0

# Focus & Input
drag_tile_to_tile=1
warpcursor=1
cursor_hide_timeout=5
drag_corner=0
focus_on_activate=1
sloppyfocus=1

# Cursor Theme
cursor_theme=Bibata-Modern-Classic
cursor_size=32

# Theming
borderpx=3
gappih=10
gappiv=10
gappoh=10
gappov=10
focused_opacity=1.0

rootcolor=0x201b14ff
maximizescreencolor=0xffffffff
urgentcolor=0xad401fff
globalcolor=0xb153a7ff
scratchpadcolor=0x516c93ff
overlaycolor=0x14a57cff
focuscolor=0xffffffff
bordercolor=0x44444400
