# window rules
windowrule=title:Authentication required,isfloating:1
windowrule=title:Keybindings,isfloating:1
windowrule=title:Rename*,isfloating:1
windowrule=title:Compressing*,isfloating:1
windowrule=title:File Already Exists*,isfloating:1
windowrule=title:Extracting Files*,isfloating:1
windowrule=title:File Operation Progress*,isfloating:1
windowrule=title:Confirm to replace files*,isfloating:1
windowrule=appid:clipse,isfloating:1,width:600,height:800
windowrule=title:Mission Center,isfloating:1,width:1400,height:800
windowrule=offsety:96%,offsetx:98%,isnoborder:1,isopensilent:1,isoverlay:1,isfloating:1,width:440,height:220,title:Picture-in-Picture
windowrule=offsety:96%,offsetx:98%,isnoborder:1,isopensilent:1,isoverlay:1,isfloating:1,width:440,height:220,title:Picture in picture
windowrule=appid:org.kde.kdeconnect.daemon,offsety:90%,offsetx:98%,isfloating:1,allow_csd:0,width:500,height:280
windowrule=appid:org.kde.kdeconnect.handler,offsety:90%,offsetx:98%,isfloating:1,allow_csd:0,width:500,height:280
windowrule=appid:nmtui,offsety:96%,offsetx:98%,isfloating:1,width:1000,height:580
windowrule=appid:bluetui,offsety:96%,offsetx:98%,isfloating:1,width:1000,height:580
windowrule=appid:org.kde.kdeconnect.sms,offsety:96%,offsetx:98%,isfloating:1,width:1000,height:580
windowrule=appid:dashboard,offsety:97%,offsetx:98%,isfloating:1,isnoborder:1,width:640,height:340
windowrule=appid:launcher,offsety:100%,offsetx:0%,isfloating:1,width:580,height:340
windowrule=appid:powermenu,offsety:-90%,offsetx:95%,isfloating:1,width:400,height:240
windowrule=appid:clipboard,offsety:96%,offsetx:-98%,isfloating:1,width:960,height:560
windowrule=appid:aichat,offsety:96%,offsetx:98%,isfloating:1,width:1000,height:580
# windowrule=appid:thunar,offsety:96%,offsetx:98%,isfloating:1,width:860,height:520
windowrule=appid:org.kde.kdeconnect.app,offsety:96%,offsetx:98%,isfloating:1,width:980,height:575
windowrule=appid:localsend,offsety:96%,offsetx:98%,isfloating:1,allow_csd:0,width:900,height:540
windowrule=appid:org.gnome.Nautilus,offsety:96%,offsetx:98%,isfloating:1,width:1000,height:580
windowrule=appid:cava,offsety:1080,offsetx:100%,isnoborder:1,isopensilent:1,isfloating:1,width:1919,height:160
windowrule=title:clip-qr.png,offsety:-96%,offsetx:-98%,isfloating:1,width:400,height:400
windowrule=monitor:DP-2,tags:9,appid:conky
windowrule=monitor:DP-1,tags:1,appid:zen-browser


# Layer rules
layerrule=noanim:1,noblur:1,layer_name:selection
