# layout support:

# tagrule=id:1,layout_name:scroller
# tagrule=id:2,layout_name:fair
# tagrule=id:3,layout_name:dwindle
# tagrule=id:4,layout_name:right_tile
# tagrule=id:5,layout_name:right_tile
# tagrule=id:6,layout_name:right_tile
# tagrule=id:7,layout_name:right_tile
# tagrule=id:8,layout_name:right_tile
# tagrule=id:9,layout_name:right_tile

tagrule=id:1,monitor_name:DP-1,layout_name:scroller
tagrule=id:2,monitor_name:DP-1,layout_name:scroller
tagrule=id:3,monitor_name:DP-1,layout_name:scroller
tagrule=id:4,monitor_name:DP-1,layout_name:scroller
tagrule=id:5,monitor_name:DP-1,layout_name:scroller

tagrule=id:6,monitor_name:DP-2,layout_name:scroller
tagrule=id:7,monitor_name:DP-2,layout_name:scroller
tagrule=id:8,monitor_name:DP-2,layout_name:scroller
tagrule=id:9,monitor_name:DP-2,layout_name:scroller
tagrule=id:0,monitor_name:DP-2,layout_name:scroller