[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"

[[manager.prepend_keymap]]
on   = [ "i" ]
run = "plugin easyjump"
desc = "easyjump"

# keymap.toml
[[mgr.prepend_keymap]]
on   = "<C-w>"
for  = "linux"
run  = "shell -- hyprctl hyprpaper reload ,%h"
desc = "Set hovered file as wallpaper"