# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e3e3d8"

# Title color for boxes
theme[title]="#b5d086"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#c1caab"

# Background color of selected item in processes box
theme[selected_bg]="#b5d086"

# Foreground color of selected item in processes box
theme[selected_fg]="#233600"

# Color of inactive/disabled text
theme[inactive_fg]="#c5c8b9"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#a0d0c9"

# Cpu box outline color
theme[cpu_box]="#8f9284"

# Memory/disks box outline color
theme[mem_box]="#8f9284"

# Net up/down box outline color
theme[net_box]="#8f9284"

# Processes box outline color
theme[proc_box]="#8f9284"

# Box divider line and small boxes line color
theme[div_line]="#45483d"

# Temperature graph colors
theme[temp_start]="#c1caab"
theme[temp_mid]="#b5d086"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#c1caab"
theme[cpu_mid]="#b5d086"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#c1caab"
theme[free_mid]=""
theme[free_end]="#414a32"

# Mem/Disk cached meter
theme[cached_start]="#a0d0c9"
theme[cached_mid]=""
theme[cached_end]="#1f4e49"

# Mem/Disk available meter
theme[available_start]="#b5d086"
theme[available_mid]=""
theme[available_end]="#384d12"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#c1caab"
theme[download_mid]="#b5d086"
theme[download_end]="#a0d0c9"

# Upload graph colors
theme[upload_start]="#c1caab"
theme[upload_mid]="#b5d086"
theme[upload_end]="#a0d0c9"