[colors]
background = '#141218'
foreground = '#e7e0e8'

cursor_bg = '#d2bcfd'
cursor_fg = '#141218'
cursor_border = '#d2bcfd'

selection_bg = '#4f3d74'
selection_fg = '#e7e0e8'

ansi = ['#141218', '#ff728e', '#7efd99', '#ffda72', '#bfa6f0', '#503d75', '#d2bcfd', '#f4efff']
brights = ['#9c98a4', '#ff9fb2', '#a5ffb9', '#ffe7a5', '#dac7ff', '#e0d1ff', '#ebe1ff', '#faf8ff']
