[colors]
background = '#121318'
foreground = '#e3e2e9'

cursor_bg = '#b3c5ff'
cursor_fg = '#121318'
cursor_border = '#b3c5ff'

selection_bg = '#324578'
selection_fg = '#e3e2e9'

ansi = ['#121318', '#e54d45', '#6ed66e', '#dbd37b', '#667cd6', '#919cbf', '#b3c5ff', '#abb2bf']
brights = ['#5c6370', '#e0615f', '#86e086', '#e8e197', '#bfd3ff', '#577ab2', '#6f74b7', '#ffffff']
