[colors.primary]
background = '#121318'
foreground = '#e3e2e9'

[colors.selection]
text = '#e3e2e9'
background = '#324578'

[colors.cursor]
text = '#121318'
cursor = '#b3c5ff'

[colors.normal]
black   = '#121318'
red     = '#e54d45'
green   = '#6ed66e'
yellow  = '#dbd37b'
blue    = '#667cd6'
magenta = '#919cbf'
cyan    = '#b3c5ff'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e0615f'
green   = '#86e086'
yellow  = '#e8e197'
blue    = '#bfd3ff'
magenta = '#577ab2'
cyan    = '#6f74b7'
white   = '#ffffff'
