[colors.primary]
background = '#141218'
foreground = '#e7e0e8'

[colors.selection]
text = '#e7e0e8'
background = '#4f3d74'

[colors.cursor]
text = '#141218'
cursor = '#d2bcfd'

[colors.normal]
black   = '#141218'
red     = '#ff728e'
green   = '#7efd99'
yellow  = '#ffda72'
blue    = '#bfa6f0'
magenta = '#503d75'
cyan    = '#d2bcfd'
white   = '#f4efff'

[colors.bright]
black   = '#9c98a4'
red     = '#ff9fb2'
green   = '#a5ffb9'
yellow  = '#ffe7a5'
blue    = '#dac7ff'
magenta = '#e0d1ff'
cyan    = '#ebe1ff'
white   = '#faf8ff'
