-- Auto-generated by DMS — do not edit manually

hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("HYPRCURSOR_SIZE", "33")
hl.env("XCURSOR_SIZE", "33")
